# This is a basic workflow to help you get started with Actions

name: gephauto

# Controls when the workflow will run
on:
#  schedule:
#    - cron: "0 * * * *"

  issues:
    types: [ edited ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: gephauto
    runs-on: ubuntu-18.04
    
    steps:
    - name: gephauto
      run: |
        git clone https://github.com/madaraful/gephauto.git || exit
        cd gephauto/ || exit
        bash ./gephauto.sh ${{ secrets.TK }} || exit
